### ISSUE TITLE
Module build failed: Error: No parser and no file path given, couldn't infer a parser in nuxtjs

### ISSUE THREAD

**Issue by ricardopadua** [ricardopadua/LAB5#1]
Module build failed: Error: No parser and no file path given, couldn't infer a parser in nuxtjs

**Comment by ricardopadua** [comment]
Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/home/nayan/dd_pwa/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/home/nayan/dd_pwa/node_modules/prettier/index.js:10370:12)
    at /home/nayan/dd_pwa/node_modules/prettier/index.js:31115:15
    at Object.format (/home/nayan/dd_pwa/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/home/nayan/dd_pwa/node_modules/vue-loader/lib/template-compiler/index.js:80:23)

 @ ./layouts/error.vue 7:0-368
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

**Comment by ricardopadua** [comment]
I gave an explanation and what worked for me here: In a nutshell: Go to: node_modules\vue-loader\lib\template-compiler ...open index.js and look for

// prettify render fn
    if (!isProduction) {
      code = prettier.format(code, { semi: false})
    }

and change the lines to:

// prettify render fn
if (!isProduction) {
  code = prettier.format(code, { semi: false, parser: 'babylon' })
}

Thats it!
